### ISSUE TITLE
Parse errors are not instances of `DotParseError`

### ISSUE THREAD

**Issue by septatrix** [ts-graphviz/ts-graphviz#1259]
## Describe the bug

Errors raised due to invalid dot inputs from `parse` are not instances of the `DotSyntaxError` class/type

## To Reproduce

```typescript
import { DotSyntaxError, parse } from "ts-graphviz/ast";

let dot;
try {
    dot = parse("foobar");
} catch (error) {
    console.error(error);
    console.log(error instanceof DotSyntaxError);
}
```

## Expected behavior

The instanceof check should return true

## Additional context

It seems like the creation of the error object itself may be failing:

```txt
 ERROR  Expected "#", "/*", "//", "digraph", "graph", "strict", WHITESPACE, or whitespace but "f" found.

  at new peg$SyntaxError (node_modules/.pnpm/@ts-graphviz+ast@2.0.5/node_modules/@ts-graphviz/ast/lib/ast.js:341:24)
  at new DotSyntaxError (node_modules/.pnpm/@ts-graphviz+ast@2.0.5/node_modules/@ts-graphviz/ast/lib/ast.js:3128:5)
  at parse (node_modules/.pnpm/@ts-graphviz+ast@2.0.5/node_modules/@ts-graphviz/ast/lib/ast.js:3121:13)
  at Object.handler (server/api/render.post.ts:9:1)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async node_modules/.pnpm/h3@1.13.0/node_modules/h3/dist/index.mjs:1978:19
  at async Object.callAsync (node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (node_modules/.pnpm/h3@1.13.0/node_modules/h3/dist/index.mjs:2270:7)
```

**Comment by kamiazya** [comment]
@septatrix Thanks for reporting.

It will be fixed in the next version.

**Comment by kamiazya** [comment]
@all-contributors please add @septatrix  for bug.

**Comment by kamiazya** [comment]
@septatrixThank you for reporting a bug!

It has been fixed at [ts-graphviz@2.1.6](https://github.com/ts-graphviz/ts-graphviz/releases/tag/ts-graphviz%402.1.6).
